### ISSUE TITLE
[NumberGuesser] int.Parse(answer)

### ISSUE THREAD

**Issue by pavel-b-novikov** [S-Saturn/nsudotnet#2]
А сделайте чтобы exception не кидало при неверном вводе?

**Comment by S-Saturn** [comment]
Просто в задании конкретно не было сказано, чего там выводить) придумаю что-нибудь, ладно

On May 17, 2017 09:49, Pavel Novikov <notifications@github.com> wrote:

А сделайте чтобы exception не кидало при неверном вводе?

**Comment by S-Saturn** [comment]
Fixed
