### ISSUE TITLE
[Enigma] Декомпозиция

### ISSUE THREAD

**Issue by pavel-b-novikov** [S-Saturn/nsudotnet#5]
У вас, я смотрю, все равно Decryptor/Encryptor создаются один раз со всеми алгоритмами. Вот сделайте их Disposable с аллокацией/освобождением ресурсов через правильный Dispose pattern.

Больше придраться не нашел к чему.

**Comment by S-Saturn** [comment]
Done

**Comment by pavel-b-novikov** [comment]
Пойдет
